spring.datasource:
  url: jdbc:h2:file:~/ProcessingService;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  #hibernate.ddl-auto: none
  #generate-ddl: false
  #properties.hibernate.hbm2ddl.auto: none